### ==================== TOP LEVEL ==================== ###

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"


## WCS redirects

### Redirect all paths starting with /wcs to /cloud
[[redirects]]
from = "/wcs/*"
to   = "/cloud/:splat"
status = 301

[[redirects]]
from = "/cloud/troubleshooting"
to   = "/cloud/faq"
status = 301

[[redirects]]
from = "/cloud/platform/ssconsole"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/cloud/platform/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/cloud/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/cloud/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/cloud/conect"
to   = "/cloud/manage-clusters/connect"
status = 301

[[redirects]]
from = "/cloud/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/cloud/upgrade"
to   = "/cloud/manage-clusters/upgrade"
status = 301

[[redirects]]
from = "/cloud/guides/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/cloud/guides/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/cloud/guides/authentication"
to   = "/cloud/manage-clusters/connect"
status = 301

## Redirect starting paths "/" and "/docs" to "/weaviate"
## Redirect anything from /developers to /docs

[[redirects]]
from = "/"
to   = "/weaviate"
status = 301

## Manage data refactoring

[[redirects]]
from = "/weaviate/manage-data"
to   = "/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/weaviate/manage-data/collections"
to   = "/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/weaviate/manage-data/create"
to   = "/weaviate/manage-objects/create"
status = 301

[[redirects]]
from = "/weaviate/manage-data/import"
to   = "/weaviate/manage-objects/import"
status = 301

[[redirects]]
from = "/weaviate/manage-data/read"
to   = "/weaviate/manage-objects/read"
status = 301

[[redirects]]
from = "/weaviate/manage-data/read-all-objects"
to   = "/weaviate/manage-objects/read-all-objects"
status = 301

[[redirects]]
from = "/weaviate/manage-data/update"
to   = "/weaviate/manage-objects/update"
status = 301

[[redirects]]
from = "/weaviate/manage-data/delete"
to   = "/weaviate/manage-objects/delete"
status = 301

[[redirects]]
from = "/weaviate/manage-data/cross-references"
to   = "/weaviate/manage-collections/cross-references"
status = 301

[[redirects]]
from = "/weaviate/manage-data/multi-tenancy"
to   = "/weaviate/manage-collections/multi-tenancy"
status = 301

[[redirects]]
from = "/weaviate/manage-data/tenant-states"
to   = "/weaviate/manage-collections/tenant-states"
status = 301

[[redirects]]
from = "/weaviate/manage-data/migrate"
to   = "/weaviate/manage-collections/migrate"
status = 301

## Roadmap page redirect

[[redirects]]
from = "/weaviate/roadmap"
to   = "/weaviate/release-notes"
status = 301

## Installation redirects

[[redirects]]
from = "/weaviate/installation/weaviate-cloud-services"
to   = "/deploy/installation-guides/weaviate-cloud"
status = 301

[[redirects]]
from = "/weaviate/installation/docker-compose"
to   = "/deploy/installation-guides/docker-installation"
status = 301

[[redirects]]
from = "/weaviate/installation/kubernetes"
to   = "/deploy/installation-guides/k8s-installation"
status = 301

[[redirects]]
from = "/weaviate/installation/embedded"
to   = "/deploy/installation-guides/embedded"
status = 301

[[redirects]]
from = "/weaviate/installation/aws-marketplace"
to   = "/deploy/installation-guides/eks"
status = 301

[[redirects]]
from = "/weaviate/installation/gc-marketplace"
to   = "/deploy/installation-guides/gke-marketplace"
status = 301

[[redirects]]
from = "/weaviate/installation/spcs-integration"
to   = "/deploy/installation-guides/spcs-integration"
status = 301
