### ==================== TOP LEVEL ==================== ###

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

## WCS redirects

[[redirects]]
from = "/wcs/troubleshooting"
to   = "/cloud/faq"
status = 301

[[redirects]]
from = "/wcs/platform/ssconsole"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/wcs/platform/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/wcs/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/wcs/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/wcs/conect"
to   = "/cloud/manage-clusters/connect"
status = 301

[[redirects]]
from = "/wcs/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/wcs/upgrade"
to   = "/cloud/manage-clusters/upgrade"
status = 301

[[redirects]]
from = "/wcs/guides/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/wcs/guides/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/wcs/guides/authentication"
to   = "/cloud/manage-clusters/connect"
status = 301

## Redirect starting paths "/" and "/docs" to "/weaviate"
## Redirect anything from /developers to /docs

[[redirects]]
from = "/"
to   = "/weaviate"
status = 301

## Redirect all paths starting with /docs/wcs to /docs/cloud

[[redirects]]
from = "/docs/wcs/*"
to   = "/docs/cloud/:splat"
status = 301

## Manage data refactoring

[[redirects]]
from = "/weaviate/manage-data"
to   = "/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/weaviate/manage-data/collections"
to   = "/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/weaviate/manage-data/create"
to   = "/weaviate/manage-objects/create"
status = 301

[[redirects]]
from = "/weaviate/manage-data/import"
to   = "/weaviate/manage-objects/import"
status = 301

[[redirects]]
from = "/weaviate/manage-data/read"
to   = "/weaviate/manage-objects/read"
status = 301

[[redirects]]
from = "/weaviate/manage-data/read-all-objects"
to   = "/weaviate/manage-objects/read-all-objects"
status = 301

[[redirects]]
from = "/weaviate/manage-data/update"
to   = "/weaviate/manage-objects/update"
status = 301

[[redirects]]
from = "/weaviate/manage-data/delete"
to   = "/weaviate/manage-objects/delete"
status = 301

[[redirects]]
from = "/weaviate/manage-data/cross-references"
to   = "/weaviate/manage-collections/cross-references"
status = 301

[[redirects]]
from = "/weaviate/manage-data/multi-tenancy"
to   = "/weaviate/manage-collections/multi-tenancy"
status = 301

[[redirects]]
from = "/weaviate/manage-data/tenant-states"
to   = "/weaviate/manage-collections/tenant-states"
status = 301

[[redirects]]
from = "/weaviate/manage-data/migrate"
to   = "/weaviate/manage-collections/migrate"
status = 301

## Roadmap page redirect

[[redirects]]
from = "/weaviate/roadmap"
to   = "/weaviate/release-notes"
status = 301
