### ==================== TOP LEVEL ==================== ###

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

## WCS redirects

[[redirects]]
from = "/wcs/troubleshooting"
to   = "/cloud/faq"
status = 301

[[redirects]]
from = "/wcs/platform/ssconsole"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/wcs/platform/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/wcs/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/wcs/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/wcs/conect"
to   = "/cloud/manage-clusters/connect"
status = 301

[[redirects]]
from = "/wcs/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/wcs/upgrade"
to   = "/cloud/manage-clusters/upgrade"
status = 301

[[redirects]]
from = "/wcs/guides/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/wcs/guides/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/wcs/guides/authentication"
to   = "/cloud/manage-clusters/connect"
status = 301

## Redirect starting paths "/", "/docs" and "/docs/weaviate/introduction" to "/docs/weaviate"

[[redirects]]
from = "/developers/*"
to   = "/docs/:splat"
status = 301

[[redirects]]
from = "/docs"
to   = "/docs/weaviate"
status = 301

[[redirects]]
from = "/"
to   = "/docs/weaviate"
status = 301

[[redirects]]
from = "/docs/weaviate/introduction"
to   = "/docs/weaviate"
status = 301

## Redirects for Weaviate release notes

[[redirects]]
from = "/docs/weaviate/release-notes/older-releases/release_1_*"
to = "https://weaviate.io/blog/weaviate-1-:splat-release"
status = 301

[[redirects]]
from = "/docs/weaviate/release-notes/release_1_*"
to = "https://weaviate.io/blog/weaviate-1-:splat-release"
status = 301

## Redirect all paths starting with /docs/wcs to /docs/cloud

[[redirects]]
from = "/docs/wcs/*"
to   = "/docs/cloud/:splat"
status = 301

## Manage data refactoring

[[redirects]]
from = "/docs/weaviate/manage-data"
to   = "/docs/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/collections"
to   = "/docs/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/create"
to   = "/docs/weaviate/manage-objects/create"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/import"
to   = "/docs/weaviate/manage-objects/import"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/read"
to   = "/docs/weaviate/manage-objects/read"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/read-all-objects"
to   = "/docs/weaviate/manage-objects/read-all-objects"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/update"
to   = "/docs/weaviate/manage-objects/update"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/delete"
to   = "/docs/weaviate/manage-objects/delete"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/cross-references"
to   = "/docs/weaviate/manage-collections/cross-references"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/multi-tenancy"
to   = "/docs/weaviate/manage-collections/multi-tenancy"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/tenant-states"
to   = "/docs/weaviate/manage-collections/tenant-states"
status = 301

[[redirects]]
from = "/docs/weaviate/manage-data/migrate"
to   = "/docs/weaviate/manage-collections/migrate"
status = 301

## Roadmap page redirect

[[redirects]]
from = "/docs/weaviate/roadmap"
to   = "/docs/weaviate/release-notes"
status = 301

## Deployment redirects

[[redirects]]
from = "/docs/weaviate/installation"
to   = "/docs/deploy"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/weaviate-cloud-services"
to   = "/docs/deploy/installation-guides/weaviate-cloud"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/docker-compose"
to   = "/docs/deploy/installation-guides/docker-installation"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/kubernetes"
to   = "/docs/deploy/installation-guides/k8s-installation"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/embedded"
to   = "/docs/deploy/installation-guides/embedded"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/aws-marketplace"
to   = "/docs/deploy/installation-guides/eks"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/gc-marketplace"
to   = "/docs/deploy/installation-guides/gke-marketplace"
status = 301

[[redirects]]
from = "/docs/weaviate/installation/spcs-integration"
to   = "/docs/deploy/installation-guides/spcs-integration"
status = 301

[[redirects]]
from = "/docs/weaviate/configuration/tenant-offloading"
to   = "/docs/deploy/configuration/tenant-offloading"
status = 301

[[redirects]]
from = "/docs/weaviate/more-resources/migration"
to   = "/docs/deploy/migration"
status = 301

[[redirects]]
from = "/docs/weaviate/more-resources/migration/archive"
to   = "/docs/deploy/migration/archive"
status = 301

[[redirects]]
from = "/docs/weaviate/more-resources/migration/weaviate-1-25"
to   = "/docs/deploy/migration/weaviate-1-25"
status = 301

[[redirects]]
from = "/docs/weaviate/more-resources/migration/weaviate-1-30"
to   = "/docs/deploy/migration/weaviate-1-30"
status = 301

[[redirects]]
from = "/docs/weaviate/tutorials/rbac"
to   = "/docs/deploy/tutorials/rbac"
status = 301

[[redirects]]
from = "/docs/weaviate/config-refs/env-vars"
to   = "/docs/deploy/configuration/env-vars"
status = 301

[[redirects]]
from = "/docs/weaviate/config-refs/env-vars/runtime-config"
to   = "/docs/deploy/configuration/env-vars/runtime-config"
status = 301

## Docs migration redirects

[[redirects]]
from = "/docs/weaviate/client-libraries/typescript/typescript-v3"
to   = "/docs/weaviate/client-libraries/typescript"
status = 301

## Because baseUrl is /docs but pages are served directly under /build

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 200
  force = true
