### ==================== TOP LEVEL ==================== ###

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"


## WCS redirects

### Redirect all paths starting with /wcs to /cloud
[[redirects]]
from = "/wcs/*"
to   = "/cloud/:splat"
status = 301

[[redirects]]
from = "/cloud/troubleshooting"
to   = "/cloud/faq"
status = 301

[[redirects]]
from = "/cloud/platform/ssconsole"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/cloud/platform/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/cloud/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/cloud/cluster-status"
to   = "/cloud/manage-clusters/status"
status = 301

[[redirects]]
from = "/cloud/conect"
to   = "/cloud/manage-clusters/connect"
status = 301

[[redirects]]
from = "/cloud/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/cloud/upgrade"
to   = "/cloud/manage-clusters/upgrade"
status = 301

[[redirects]]
from = "/cloud/guides/console"
to   = "/cloud/tools/query-tool"
status = 301

[[redirects]]
from = "/cloud/guides/create-instance"
to   = "/cloud/manage-clusters/create"
status = 301

[[redirects]]
from = "/cloud/guides/authentication"
to   = "/cloud/manage-clusters/connect"
status = 301

## Redirect starting paths "/" and "/weaviate/introduction" to "/weaviate"

[[redirects]]
from = "/"
to   = "/weaviate"
status = 301

[[redirects]]
from = "/weaviate/introduction"
to   = "/weaviate"
status = 301

## Manage data refactoring

[[redirects]]
from = "/weaviate/manage-data"
to   = "/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/weaviate/manage-data/collections"
to   = "/weaviate/manage-collections"
status = 301

[[redirects]]
from = "/weaviate/manage-data/create"
to   = "/weaviate/manage-objects/create"
status = 301

[[redirects]]
from = "/weaviate/manage-data/import"
to   = "/weaviate/manage-objects/import"
status = 301

[[redirects]]
from = "/weaviate/manage-data/read"
to   = "/weaviate/manage-objects/read"
status = 301

[[redirects]]
from = "/weaviate/manage-data/read-all-objects"
to   = "/weaviate/manage-objects/read-all-objects"
status = 301

[[redirects]]
from = "/weaviate/manage-data/update"
to   = "/weaviate/manage-objects/update"
status = 301

[[redirects]]
from = "/weaviate/manage-data/delete"
to   = "/weaviate/manage-objects/delete"
status = 301

[[redirects]]
from = "/weaviate/manage-data/cross-references"
to   = "/weaviate/manage-collections/cross-references"
status = 301

[[redirects]]
from = "/weaviate/manage-data/multi-tenancy"
to   = "/weaviate/manage-collections/multi-tenancy"
status = 301

[[redirects]]
from = "/weaviate/manage-data/tenant-states"
to   = "/weaviate/manage-collections/tenant-states"
status = 301

[[redirects]]
from = "/weaviate/manage-data/migrate"
to   = "/weaviate/manage-collections/migrate"
status = 301

## Roadmap page redirect

[[redirects]]
from = "/weaviate/roadmap"
to   = "/weaviate/release-notes"
status = 301

## Deployment redirects

[[redirects]]
from = "/weaviate/installation"
to   = "/deploy"
status = 301

[[redirects]]
from = "/weaviate/installation/weaviate-cloud-services"
to   = "/deploy/installation-guides/weaviate-cloud"
status = 301

[[redirects]]
from = "/weaviate/installation/docker-compose"
to   = "/deploy/installation-guides/docker-installation"
status = 301

[[redirects]]
from = "/weaviate/installation/kubernetes"
to   = "/deploy/installation-guides/k8s-installation"
status = 301

[[redirects]]
from = "/weaviate/installation/embedded"
to   = "/deploy/installation-guides/embedded"
status = 301

[[redirects]]
from = "/weaviate/installation/aws-marketplace"
to   = "/deploy/installation-guides/eks"
status = 301

[[redirects]]
from = "/weaviate/installation/gc-marketplace"
to   = "/deploy/installation-guides/gke-marketplace"
status = 301

[[redirects]]
from = "/weaviate/installation/spcs-integration"
to   = "/deploy/installation-guides/spcs-integration"
status = 301

[[redirects]]
from = "/weaviate/configuration/tenant-offloading"
to   = "/deploy/configuration/tenant-offloading"
status = 301

[[redirects]]
from = "/weaviate/more-resources/migration"
to   = "/deploy/migration"
status = 301

[[redirects]]
from = "/weaviate/more-resources/migration/archive"
to   = "/deploy/migration/archive"
status = 301

[[redirects]]
from = "/weaviate/more-resources/migration/weaviate-1-25"
to   = "/deploy/migration/weaviate-1-25"
status = 301

[[redirects]]
from = "/weaviate/more-resources/migration/weaviate-1-30"
to   = "/deploy/migration/weaviate-1-30"
status = 301

[[redirects]]
from = "/weaviate/tutorials/rbac"
to   = "/deploy/tutorials/rbac"
status = 301

[[redirects]]
from = "/weaviate/config-refs/env-vars"
to   = "/deploy/configuration/env-vars"
status = 301

[[redirects]]
from = "/weaviate/config-refs/env-vars/runtime-config"
to   = "/deploy/configuration/env-vars/runtime-config"
status = 301

# Redirects for Weaviate release notes

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_16"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_16"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_17"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_17"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_18"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_18"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_19"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_19"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_20"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_20"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_21"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_21"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_22"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_22"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_23"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_23"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_24"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_24"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_25"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_25"
status = 301

[[redirects]]
from = "/weaviate/release-notes/older-releases/release_1_26"
to   = "https://weaviate.io/developers/weaviate/release-notes/older-releases/release_1_26"
status = 301

[[redirects]]
from = "/weaviate/release-notes/release_1_27"
to   = "https://weaviate.io/developers/weaviate/release-notes/release_1_27"
status = 301

[[redirects]]
from = "/weaviate/release-notes/release_1_28"
to   = "https://weaviate.io/developers/weaviate/release-notes/release_1_28"
status = 301

[[redirects]]
from = "/weaviate/release-notes/release_1_29"
to   = "https://weaviate.io/developers/weaviate/release-notes/release_1_29"
status = 301

[[redirects]]
from = "/weaviate/release-notes/release_1_30"
to   = "https://weaviate.io/developers/weaviate/release-notes/release_1_30"
status = 301

[[redirects]]
from = "/weaviate/release-notes/release_1_31"
to   = "https://weaviate.io/developers/weaviate/release-notes/release_1_31"
status = 301

# Docs migration redirects

[[redirects]]
from = "/weaviate/client-libraries/typescript/typescript-v3"
to   = "/weaviate/client-libraries/typescript"
status = 301
